#!/usr/bin/env bash

# git cleanup-branches
# Adopt from https://www.hardscrabble.net/2018/git-cleanup-branches/
# Modified to support remote branch

set -euo pipefail

LIST_BRANCH_FLAGS=
DELETE_BRANCH_FLAGS="-D"

while getopts "r" arg; do
  case $arg in
    r)
      echo "TEST"
      LIST_BRANCH_FLAGS="-r"
      DELETE_BRANCH_FLAGS="-r -d"
      ;;
  esac
done

file="/tmp/git-cleanup-branches-$(uuidgen)"

function removeCurrentBranch {
  sed -E '/\*/d'
}

function leftTrim {
  sed -E 's/\*?[[:space:]]+//'
}


all_branches=$(git branch ${LIST_BRANCH_FLAGS}| removeCurrentBranch | leftTrim)

# write branches to file
for branch in $all_branches; do
  echo "keep $branch" >> $file
done

# write instructions to file
echo "

# All of your branches are listed above
# (except for the current branch, which you can't delete)
# change keep to d to delete the branch
# all other lines are ignored" >> $file

# prompt user to edit file
$EDITOR "$file"

# check each line of the file
cat $file | while read -r line; do

  # if the line starts with "d "
  if echo $line | grep --extended-regexp "^d " > /dev/null; then
    # delete the branch
    branch=$(echo $line | sed -E 's/^d //')

    git branch ${DELETE_BRANCH_FLAGS} $branch
  fi
done

# clean up
rm $file
